version: "3.7"

services:
  proxy:
    container_name: proxy
    image: nginx:alpine
    depends_on:
      - "app"
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1

  config:
    container_name: config
    build:
      context: .
      dockerfile: Dockerfile.app
    command: /appserver static --port=80 -m /:/app/config
    ports:
      - "8000:80"

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.app
    command: /appserver auth -c app.json -c sms_gateways==sms_gateways.json -c port=3000
    environment:
      APP_SECRET: $APP_SECRET
      DB_SECRET: $DB_SECRET
      STRIPE_SECRET_KEY: $STRIPE_SECRET_KEY
      STRIPE_PUBLISHABLE_KEY: $STRIPE_PUBLISHABLE_KEY
      STRIPE_WEBHOOK_SECRET: $STRIPE_WEBHOOK_SECRET
      GOOGLE_CLIENT_ID: $GOOGLE_CLIENT_ID
      GOOGLE_CLIENT_SECRET: $GOOGLE_CLIENT_SECRET
      LINKEDIN_CLIENT_ID: $LINKEDIN_CLIENT_ID
      LINKEDIN_CLIENT_SECRET: $LINKEDIN_CLIENT_SECRET
      TWILIO_ACCOUNT_ID: $TWILIO_ACCOUNT_ID
      TWILIO_AUTH_TOKEN: $TWILIO_AUTH_TOKEN
      TWILIO_FROM: $TWILIO_FROM
      TWILIO_SERVICE_SID: $TWILIO_SERVICE_SID
      EMAIL_FROM: $EMAIL_FROM
      EMAIL_TO: $EMAIL_TO
      EMAIL_HOST: $EMAIL_HOST
      EMAIL_USER: $EMAIL_USER
      EMAIL_PASSWORD: $EMAIL_PASSWORD
    depends_on:
      - "config"
      - "db"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  db:
    container_name: db
    build:
      context: .
      dockerfile: Dockerfile.db
    restart: always
    volumes:
      - appdb:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: api
      POSTGRES_PASSWORD: $DB_SECRET
      PGDATA: /var/lib/postgresql/data/pgdata

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  appdb:
